name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:      
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: "⚙ environment"
        run: |
          sudo apt-get install -qq libcairo2

          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install 'standardebooks==2.6.4'

      - name: "🔎 lint"
        id: get_errors
        run: |
          se lint .

      - name: "✂ build image"
        run: se build-images.

      - name: "🔧 build book"
        run: |
          se build --kobo .
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: "🚀 release" 
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          make_latest: true
          # body_path: CHANGELOG.md
          files: "*.epub"
